
# Create a Secrets Manager secret to store user passwords
resource "aws_secretsmanager_secret" "user_passwords"{
   for_each = aws_iam_user.users
   name = "iam/initial-passwords/${each.value.name}"

   # for testing purposes, we can set a short recovery window. In production, you might want to set this to a longer period or disable it entirely.
   recovery_window_in_days = 0 
}
# Store the password generated by the login profile in the secret
resource "aws_secretsmanager_secret_version" "password" {
    for_each = aws_iam_user.users
    secret_id = aws_secretsmanager_secret.user_passwords[each.key].id

    # Reference the passowrd from login profile resource
    secret_string = aws_iam_user_login_profile.users[each.key].password
}